---
name: Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.app-name }} (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        django-version: [5.0]
        app-name: [core]
      
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.test.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt

      - name: Run tests
        run: |
          coverage run manage.py test core/tests
          coverage report

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.app-name }} (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})